override:
  value: 'from application.yml'
server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://emptysaverdb.cf14z15rwal6.ap-northeast-2.rds.amazonaws.com:3306/emptysaver?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true
    username: emptysaver
    password: emptysaver
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default-batch-size: 200
    show-sql: true


jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400


